modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="ashihara"
version="${file.jarVersion}"
displayName="Ashihara"
logoFile="ashihara.png"
credits="Author Kogasa Studio, everyone attending this test, Syameimaru zheng, 3TUSK, Zomb_076, Morning, MalayP, and YAOYOROZUKAMI"
authors="Kogasastudio"
description='''
A mod which adds tons of japanese elements
'''
[[dependencies.ashihara]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ashihara]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
